import { DEFAULT_SPEED } from "../config"

export const PROGRESSION_TAG = "ZLJ_PROGRESSION"

export const MOVEMENT_EXP_TICK_SECONDS = 0.2
export const MOVEMENT_EXP_PER_WORLD_UNIT = 1
export const MOVEMENT_EXP_MIN_DISTANCE = 0.05
export const MOVEMENT_EXP_MAX_DISTANCE_PER_TICK = 60
export const MOVEMENT_EXP_MAX_PER_SECOND = 200

export const TEMP_BASE_SPEED = DEFAULT_SPEED
export const TEMP_SPEED_PER_LEVEL = 1
export const TEMP_MAX_SPEED = 1000

export const PROGRESS_BAR_MAX = 1000
export const FLOATING_TEXT_ENABLED = false
export const WORLD_FLOATING_TEXT_ENABLED = true
export const FLOATING_TEXT_VISIBLE_SECONDS = 0.65
export const FLOATING_TEXT_FADE_SECONDS = 0.18

export const EXPERIENCE_SCREEN_WIDTH = 2152
export const EXPERIENCE_SCREEN_HEIGHT = 1080
export const EXPERIENCE_SCREEN_FLOAT_POOL_SIZE = 6
export const EXPERIENCE_SCREEN_FLOAT_FONT_SIZE = 50
export const EXPERIENCE_SCREEN_FLOAT_WIDTH = 360
export const EXPERIENCE_SCREEN_FLOAT_HEIGHT = 72
export const EXPERIENCE_SCREEN_FLOAT_X_MIN = 90
export const EXPERIENCE_SCREEN_FLOAT_X_MAX = 520
export const EXPERIENCE_SCREEN_FLOAT_Y_MIN = 790
export const EXPERIENCE_SCREEN_FLOAT_Y_MAX = 980
export const EXPERIENCE_SCREEN_FLOAT_SECONDS = 0.75
